Feat/movj action server #109
HarvestX/MG400_ROS2 pull request #109
Opened 2022-10-31 04:33 UTC by Mt-is-at-O

2022-10-31 09:16 UTC, Mt-is-at-O commented
１つ目のターミナル
`ros2 launch mg400_bringup mg400.launch.py`
２つ目のターミナル
`. sample.bash`
よりactionを用いた動きを見れる

2022-10-31 13:18 UTC, m12watanabe1a commented
@Mt-is-at-O
Thank you for the implementation.
Your code was almost perfect. And I changed a bit for implementation simplicity.


And note that the`mov_j` msg interface has been changed by this PR,
So the other repos will be affected.

2022-10-31 13:20 UTC, m12watanabe1a requested changes

2022-10-31 13:20 UTC, m12watanabe1a commented on mg400_bringup/launch/mg400.launch.py
> +            {'ip_address': ip_address,
This is not needed

2022-10-31 13:20 UTC, m12watanabe1a commented on mg400_bringup/launch/mg400.launch.py
> +             'action_level': action_level}])
This also is not needed for now

2022-10-31 13:20 UTC, m12watanabe1a commented on mg400_bringup/launch/mg400.launch.py
> +    ld.add_action(action_level_arg)
this also

2022-10-31 13:20 UTC, m12watanabe1a commented on mg400_bringup/launch/simulator.launch.py
> +            ('action_level', action_level)])
This also

2022-10-31 13:24 UTC, m12watanabe1a approved these changes

2022-10-31 13:24 UTC, m12watanabe1a commented on mg400_node/src/action_node.cpp
> +         is_in_tolerance(this->current_end_pose_.z - goal.z);
`current_end_pose.r` also should be checked in future PR

2022-10-31 13:27 UTC, m12watanabe1a commented
We need check this PR with real HW again

2022-11-01 01:35 UTC, m12watanabe1a commented
Now it is confirmed to work

2022-11-01 01:53 UTC, merged

2022-11-01 04:58 UTC, m12watanabe1a commented on mg400_node/src/action_node.cpp
> +         is_in_tolerance(this->current_end_pose_.z - goal.z);
This requirements has been solved in this PR.