handling mg400 network disconnection
HarvestX/MG400_ROS2 pull request #167
Opened 2023-04-24 10:47 UTC by ynyBonfennil

2023-04-25 11:37 UTC, m12watanabe1a requested changes
Thank you so much for the change.
Please check out the commnet above.

2023-04-25 11:37 UTC, m12watanabe1a commented on mg400_interface/src/tcp_interface/motion_tcp_interface.cpp
>  void MotionTcpInterface::checkConnection()
I think here this loop can be much simplify as like follows.

```cpp
void MotionTcpInterface::checkConnection()
{
  using namespace std::chrono_literals; // NOLINT
  while (this->is_running_.load()) {
    try {
      if (this->tcp_socket_->isConnected()) {
        std::this_thread::sleep_for(1s);
        continue;
      } else {
        this->tcp_socket_->connect(1000);
      }
    } catch (const TcpSocketException & err) {
      this->tcp_socket_->disConnect();
      RCLCPP_ERROR(this->getLogger(), "Tcp recv error : %s", err.what());
      return;
    }
  }
}
```

2023-04-25 11:37 UTC, m12watanabe1a commented on mg400_interface/src/tcp_interface/dashboard_tcp_interface.cpp
>  void DashboardTcpInterface::checkConnection()
This method also can be simplified

```cpp
void DashboardTcpInterface::checkConnection()
{
  using namespace std::chrono_literals;  // NOLINT
  while (this->is_running_.load()) {
    try {
      if (this->tcp_socket_->isConnected()) {
        std::this_thread::sleep_for(1s);
        continue;
      } else {
        this->tcp_socket_->connect(1000);
      }
    } catch (const TcpSocketException & err) {
      this->tcp_socket_->disConnect();
      RCLCPP_ERROR(this->getLogger(), "Tcp recv error : %s", err.what());
      return;
    }
  }
}
```

2023-04-25 11:37 UTC, m12watanabe1a commented on mg400_interface/src/tcp_interface/tcp_socket_handler.cpp
> +void TcpSocketHandler::connect(const uint32_t timeout)
Why don't you use chrono::nanoseconds for more simplifications and readability.

```bash
void TcpSocketHandler::connect(const std::chrono::nanoseconds timeout)
{
  if (this->fd_ < 0) {
    this->fd_ = ::socket(AF_INET, SOCK_STREAM, 0);
    if (this->fd_ < 0) {
      throw TcpSocketException(this->toString() + std::string(" socket : ") + strerror(errno));
    }

    timeval tv = {0, 0};
    tv.tv_sec = timeout.count() / 1000000;
    tv.tv_usec = (timeout.count() % 1000000);
```

2023-04-25 11:37 UTC, m12watanabe1a commented on mg400_interface/src/tcp_interface/realtime_feedback_tcp_interface.cpp
> +  while (true) {
Here also can be simplified like the above.
The points are,
1. load `is_running_` atomic member at the while condition.
2. Remove double catch method for the same exception and the same post-catche process.
3. No need to store flase into `is_runnning_` member because main thread never refer this.

2023-04-25 11:37 UTC, m12watanabe1a commented on mg400_interface/src/tcp_interface/tcp_socket_handler.cpp
> +void TcpSocketHandler::connect(const uint32_t timeout)
PS. I also want you to change `recv` method timeout implementations.

2023-04-25 12:33 UTC, ynyBonfennil commented
Thank you for your comments. Indeed those methods were not implemented properly. I've fixed them in 392d596 and 51d891b. Please check them again.

2023-04-26 02:41 UTC, m12watanabe1a approved these changes
LGTM

2023-04-26 02:53 UTC, merged