For check command
HarvestX/MG400_ROS2 pull request #74
Opened 2022-08-18 08:37 UTC by YukiYamamoto-source

# Changes

- モックの挙動をテストするために，いくつかサービスを追加しました．
- [このバグ](https://github.com/HarvestX/MG400_Mock/pull/25)の発見に役立ちました．

2022-08-18 09:40 UTC, m12watanabe1a requested changes
ちょっと追実装の記述を依頼してしまっているのですが，同時にこのブランチで実装いただけますと幸いです．

2022-08-18 09:40 UTC, m12watanabe1a commented on .vscode/cspell.json
> +    "backdrive",
@YukiYamamoto-source  余談なんですが，個々の単語の並びかえってどうやってやってますか？

2022-08-18 09:40 UTC, m12watanabe1a commented on .vscode/settings.json
> +    "python.autoComplete.extraPaths": [
space 4 -> 2による差分はできれば含めたくないです．．．

2022-08-18 09:40 UTC, m12watanabe1a commented on mg400_node/src/service_node.cpp
> +  this->speed_factor_srv_ =
サービスをめちゃくちゃ起動するとコストが増すので，起動時にできれば星三つのサービス起動版と星三つと星二つのサービス起動版で分岐させたいです．（service_level, 1, 2, 3みたいなパラメータを追加して，Switch分でどれ起動するか分岐する実装を想定）

2022-08-18 09:47 UTC, YukiYamamoto-source commented on .vscode/settings.json
> +    "python.autoComplete.extraPaths": [
申し訳ないです．．． 日ごろjsonファイルのオートフォーマットを有効にしているのを切り忘れてました．

2022-08-18 09:56 UTC, YukiYamamoto-source commented on .vscode/cspell.json
> +    "backdrive",
特に設定をした覚えがない(setting.jsonにもない)ので，ctrl+.で開くメニューから追加すると自動で並びわかると思います．

2022-08-18 09:59 UTC, YukiYamamoto-source commented on mg400_node/src/service_node.cpp
> +  this->speed_factor_srv_ =
わかりました！
追実装の記述とは，この件ですか？それとも，私がコメントアウトで記述していた部分ですか？

2022-08-18 13:49 UTC, m12watanabe1a commented on mg400_node/src/service_node.cpp
> +  this->speed_factor_srv_ =
こちらの件になります！
コメントアウト部分のサービスの初期化処理については書かなくても大丈夫です

2022-08-18 13:51 UTC, m12watanabe1a commented on .vscode/settings.json
> +    "python.autoComplete.extraPaths": [
大丈夫です！
フォーマット有効のままでsettings.jsonの中でタブのデフォルトをスペース２つ分にセットしてもらえると、助かります :pray:

2022-08-19 02:20 UTC, m12watanabe1a commented
文字列でパラメータを渡すと、実行の際に
```bash
ros2 run mg400_node service_server --ros-args -p service_level:=service_level_1
```
のような感じで記述が冗長になるのでInt型での実行に戻しました。

2022-08-19 02:23 UTC, m12watanabe1a commented
GetErrorIDに関しては、エラーのIDを文字列として取得したいという要望より、エラーの内容を画面に出してほしいという要望が強いので、サービスとしてIDを仲介するコードを実装する利得はあまりないので大丈夫です。。。！

2022-08-19 02:25 UTC, YukiYamamoto-source commented
わかりました，そっちのほうが良いですね！あおいさんに書いていただいたdeclear_parameterの使い方を知らなかったので，enum classでの実装ができなかった経緯もあります．勉強になりました！

GetErrorIDのほうも承知いたしました！

2022-08-19 02:26 UTC, m12watanabe1a commented
GetErrorIDはタイマーループで回っていて’、ロボットのステートがErrorのときに実行されるようになっています。
https://github.com/HarvestX/MG400_ROS2/blob/for_check_command/mg400_node/src/service_node.cpp#L228-L250

2022-08-19 02:27 UTC, m12watanabe1a commented
エラーステートかどうかはrealtime_tcp_packetのロボットステートを見てますね。

2022-08-19 02:31 UTC, YukiYamamoto-source commented
なるほど，エラーはかせて確認してみます！
モックのErrorIDやRobotModeの遷移は，実機と沿っていないと思うので，時間があるときに調整いただけるとありがたいです．

2022-08-19 02:33 UTC, YukiYamamoto-source commented
ちょっとモックの話になってしまいますが，ダッシュボードポートが返す文字列も実機とそっていない可能性があるのでユニットテストの際にご確認いただけるとありがたいです．いちおう，ドキュメント見てそれっぽくはしています．

2022-08-19 02:41 UTC, m12watanabe1a commented
承知しました！

2022-08-19 02:42 UTC, m12watanabe1a approved these changes

2022-08-19 02:42 UTC, merged